import json
import logging
import re
import subprocess
from pathlib import Path

from crewai import Agent
from crewai.tasks.task_output import TaskOutput

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path("output")


def _write_project_files(task_output: TaskOutput) -> None:
    """CrewAI task callback: parse JSON manifest from LLM output and write files."""
    raw = task_output.raw if hasattr(task_output, "raw") else str(task_output)

    # Extract the JSON block from fenced code block
    match = re.search(r"```json\s*(\{.*?\})\s*```", raw, re.DOTALL)
    if not match:
        # Try bare JSON object as fallback
        match = re.search(r"(\{[^{}].*\})", raw, re.DOTALL)

    if not match:
        logger.error("Builder: no JSON manifest found in output")
        return

    try:
        manifest: dict[str, str] = json.loads(match.group(1))
    except json.JSONDecodeError as exc:
        logger.error("Builder: JSON parse error: %s", exc)
        return

    # Derive slug from first key's top-level dir or fallback
    slug = list(manifest.keys())[0].split("/")[0] if manifest else "project"
    project_dir = OUTPUT_DIR / slug
    project_dir.mkdir(parents=True, exist_ok=True)

    for rel_path, content in manifest.items():
        file_path = project_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
        logger.info("Wrote %s", file_path)

    # Git init
    try:
        subprocess.run(["git", "init"], cwd=project_dir, check=True, capture_output=True)
        subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", "Initial commit — generated by trend_to_product"],
            cwd=project_dir,
            check=True,
            capture_output=True,
        )
        logger.info("Git repo initialised at %s", project_dir)
    except subprocess.CalledProcessError as exc:
        logger.warning("Git init failed: %s", exc)


def make_builder_agent(config: dict) -> Agent:
    return Agent(
        role=config["role"],
        goal=config["goal"],
        backstory=config["backstory"],
        llm="claude-opus-4-6",
        verbose=True,
        max_iter=3,
        max_tokens=32768,
    )
