import logging
import re
import subprocess
from pathlib import Path

from crewai import Agent

from tools.file_writer import FileWriterTool

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path("output")


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:40]


def git_init(project_dir: Path) -> None:
    try:
        subprocess.run(["git", "init"], cwd=project_dir, check=True, capture_output=True)
        subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", "Initial commit — generated by trend_to_product"],
            cwd=project_dir,
            check=True,
            capture_output=True,
        )
        logger.info("Git repo initialised at %s", project_dir)
    except subprocess.CalledProcessError as exc:
        logger.warning("Git init failed: %s", exc)


def make_builder_agent(config: dict) -> Agent:
    return Agent(
        role=config["role"],
        goal=config["goal"],
        backstory=config["backstory"],
        tools=[FileWriterTool()],
        llm="anthropic/claude-opus-4-6",
        verbose=True,
        max_iter=25,
    )
